services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - $NGINX_DATA/config:/etc/nginx/conf.d
      - $NGINX_DATA/ssl:/etc/nginx/ssl
      - $NGINX_DATA/www:/usr/share/nginx/html
    depends_on:
      - home-db
    restart: always
    networks:
      - service-network
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    user: 200:200
    volumes:
      - $NEXUS_DATA:/nexus-data
      - $NEXUS_DATA/etc/nexus.properties:/opt/sonatype/nexus/etc/nexus.properties
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Djava.util.prefs.userRoot=/nexus-data/javaprefs
    expose:
      - "8081"
    restart: always
    networks:
      - service-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - home-db
    restart: always
    networks:
      - service-network
  home-db:
    image: postgres:latest
    container_name: home-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - ~/.senv
    ports:
      - "16432:5432"
    volumes:
      - $POSTGRES_DATA/init.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql
    restart: always
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
