FROM ubuntu:24.04

# Ustaw zmienne środowiskowe dla nieinteraktywnej instalacji
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Warsaw

# Zaktualizuj system i zainstaluj podstawowe narzędzia
RUN apt-get update && \
    apt-get install -y \
    curl \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Uruchom przy starcie kontenera polecenie instalacyjne
CMD curl -s https://raw.githubusercontent.com/Koziolek/koziolek-configuration/refs/heads/master/initial_packages.sh | bash
