#!/bin/bash

PROJECT_NAME='koziolek-configuration'

SUDO=''
if (( $EUID != 0 )); then
    SUDO='sudo'
fi

$SUDO apt update
$SUDO apt-get install -y git vim thefuck xdotool neofetch tmux hub curl gnupg2 apt-transport-https ca-certificates \
  software-properties-common libatomic1 libgconf-2-4 libgdk-pixbuf2.0-0 libgl1-mesa-glx libegl1-mesa \
  libxcb-xtest0 libxcb-xinerama0 htop libheif-examples unzip zip

cd $HOME/ || return

[ -d $HOME/workspace/ ] || mkdir workspace
cd workspace || return

if [ ! -d "$HOME/workspace/${PROJECT_NAME}" ]; then
    git clone "https://github.com/Koziolek/${PROJECT_NAME}.git"
    ln -s "$HOME/workspace/${PROJECT_NAME}" ".${PROJECT_NAME}"
fi

if [ ! -L $HOME/.${PROJECT_NAME} ] && [ ! -d $HOME/.${PROJECT_NAME} ]; then
    ln -s $HOME/workspace/${PROJECT_NAME} $HOME/.${PROJECT_NAME}
fi

# Zmienił się sposób działania asdf
#if [ ! -d "$HOME/workspace/asdf" ]; then
#    cd $HOME/workspace
#    git clone https://github.com/asdf-vm/asdf.git
#    cd asdf || return
#    git tag -l --sort=committerdate| tail -1 | xargs git checkout -d
#
#    cd $HOME/ || return
#
#    ln -s $HOME/workspace/asdf/asdf $HOME/.asdf
#fi

curl -s "https://get.sdkman.io" | bash

source "$HOME/.sdkman/bin/sdkman-init.sh"

sdk i java
sdk i maven 
sdk i mvnd

# TODO: to trzeba jakoś inaczej ogarnąć
# curl -fsSL https://download.docker.com/linux/ubuntu/gpg | $SUDO gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | $SUDO tee /etc/apt/sources.list.d/docker.list > /dev/null
# echo "deb http://packages.azlux.fr/debian/ buster main" | $SUDO tee /etc/apt/sources.list.d/azlux.list
# wget -qO - https://azlux.fr/repo.gpg.key | $SUDO apt-key add -
#
# $SUDO apt update
# apt-cache policy docker-ce
# $SUDO apt-get install -y docker-ce docker-compose docker-ctop
# $SUDO snap install spotify
#
# cd $HOME/Pobrane/ || return
#
# wget https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
# wget https://cdn.zoom.us/prod/5.10.7.3311/zoom_amd64.deb
# wget https://repo.steampowered.com/steam/archive/precise/steam_latest.deb
#
# $SUDO apt-get install ./1password-latest.deb ./zoom_amd64.deb ./steam_latest.deb

cd $HOME/ || return
echo ". $HOME/.${PROJECT_NAME}/bash/templates/bashrc.template" >> $HOME/.bashrc
