#!/bin/bash

cat > /etc/apt/sources.list.d/azlux.sources << EOF
Types: deb
URIs: http://packages.azlux.fr/debian/
Suites: trixie
Components: main
Signed-By: /usr/share/keyrings/azlux-archive-keyring.gpg
EOF

sudo wget -O /usr/share/keyrings/azlux-archive-keyring.gpg  https://azlux.fr/repo.gpg

sudo apt-get update
sudo apt-get install docker-ctop

