bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set-option -g update-environment "CLAUDE_CODE_SSE_PORT ENABLE_IDE_INTEGRATION TERMINAL_EMULATOR"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
